### ISSUE TITLE
Rejection Criteria Point #1

### ISSUE THREAD

**Issue by njsnghl** [knockathon2015/knockathon-web#3]
@Vadi 

Rejection Criteria

Current: Point #1: So, the Knockathon starts at Friday the 11th 6:30 PM and ends at Sunday 12:01 AM (mid-night).

Expected: Point #1: So, the Knockathon starts at Friday the 11th 6:30 PM and ends at Sunday 11:59 pm (mid-night).

**Comment by Vadi** [comment]
Fixed.
